source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PagingMenuControllerDemo' do
  pod "PagingMenuController", :path => "../"
end

target 'PagingMenuControllerDemo2' do
  pod "PagingMenuController", :path => "../"
end

target 'PagingMenuControllerDemoTests' do
  pod "PagingMenuController", :path => "../"
end
